filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            within:
                brackets: true
tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.