language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: 7.2
    - php: hhvm

install:
   - mkdir -p build/bin
   - mkdir -p build/logs
   - curl -sS https://getcomposer.org/installer | php -- --install-dir=./build/bin
   - php ./build/bin/composer.phar install

script:
   - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml tests/

after_script:
   - wget --output-document=build/bin/ocular.phar https://scrutinizer-ci.com/ocular.phar
   - php ./build/bin/ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml